# Generated by Django 2.2 on 2020-06-27 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eproof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eproof_document', models.FileField(upload_to='documents/docfiles/%Y/%m/%d/')),
                ('card_image', models.FileField(upload_to='documents/docfiles/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PROPOSAL', 'proposal'), ('EPROOF', 'eproof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual')], default='miscellaneous', max_length=20)),
                ('country', models.CharField(choices=[('ALL COUNTRIES', 'All Countries'), ('BRUNEI', 'Brunei'), ('CAMBODIA', 'Cambodia'), ('HONG KONG', 'Hong Kong'), ('INDONESIA', 'Indonesia'), ('LAOS', 'Laos'), ('MALAYSIA', 'Malaysia'), ('MONGOLIA', 'Mongolia'), ('MYANMAR', 'Myanmar'), ('PAKISTAN', 'Pakistan'), ('PHILIPPINES', 'Philippines'), ('SINGAPORE', 'Singapore'), ('THAILAND', 'Thailand'), ('VIETNAM', 'Vietnam')], default='All', max_length=20)),
                ('document_file', models.FileField(upload_to='documents/docfiles/%Y/%m/%d/')),
                ('cover', models.ImageField(default='photos/images/preview1.png', upload_to='documents/covers/%Y/%m/%d/')),
                ('preview_1', models.ImageField(default='photos/images/preview1.png', upload_to='documents/previews/%Y/%m/%d/')),
                ('preview_2', models.ImageField(default='photos/images/preview1.png', upload_to='documents/previews/%Y/%m/%d/')),
                ('preview_3', models.ImageField(default='photos/images/preview1.png', upload_to='documents/previews/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default=None, max_length=100)),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PROPOSAL', 'proposal'), ('EPROOF', 'eproof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual')], default='proposal', max_length=20)),
                ('document_file', models.FileField(upload_to='documents/docfiles/%Y/%m/%d/')),
                ('cover_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/covers/%Y/%m/%d/')),
                ('image1_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/images/%Y/%m/%d/')),
                ('image2_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/images/%Y/%m/%d/')),
                ('image3_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/images/%Y/%m/%d/')),
            ],
        ),
    ]
