# Generated by Django 2.2 on 2020-06-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='preview_1',
            field=models.ImageField(default='photos/images/pic1.png', upload_to='documents/previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='preview_2',
            field=models.ImageField(default='photos/images/pic1.png', upload_to='documents/previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='preview_3',
            field=models.ImageField(default='photos/images/pic1.png', upload_to='documents/previews/%Y/%m/%d/'),
        ),
    ]
