# Generated by Django 2.2 on 2020-05-17 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='author',
            new_name='contributor',
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('ALL', 'All'), ('BRUNEI', 'Brunei'), ('CAMBODIA', 'Cambodia'), ('HONG KONG', 'Hong Kong'), ('INDONESIA', 'Indonesia'), ('LAOS', 'Laos'), ('MALAYSIA', 'Malaysia'), ('MONGOLIA', 'Mongolia'), ('MYANMAR', 'Myanmar'), ('PHILIPPINES', 'Philippines'), ('SINGAPORE', 'Singapore'), ('THAILAND', 'Thailand'), ('VIETNAM', 'Vietnam')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('PROPOSAL', 'proposal'), ('QUOTATION', 'quotation'), ('E-PROOF', 'e-proof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual'), ('MISCELLANEOUS', 'miscellaneous')], default='miscellaneous', max_length=20),
        ),
    ]
