# Generated by Django 2.2 on 2020-06-24 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_auto_20200624_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover',
            field=models.ImageField(default='photos/images/preview1.png', upload_to='documents/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='preview_1',
            field=models.ImageField(default='photos/images/preview1.png', upload_to='documents/previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='preview_2',
            field=models.ImageField(default='photos/images/preview1.png', upload_to='documents/previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='preview_3',
            field=models.ImageField(default='photos/images/preview1.png', upload_to='documents/previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('PROPOSAL', 'proposal'), ('EPROOF', 'eproof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual')], default='miscellaneous', max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PROPOSAL', 'proposal'), ('EPROOF', 'eproof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual')], max_length=20)),
                ('document_file', models.FileField(upload_to='documents/docfiles/%Y/%m/%d/')),
                ('cover_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/covers/%Y/%m/%d/')),
                ('image1_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/images/%Y/%m/%d/')),
                ('image2_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/images/%Y/%m/%d/')),
                ('image3_file', models.ImageField(default='photos/images/preview1.png', upload_to='documents/images/%Y/%m/%d/')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
