# Generated by Django 2.2 on 2020-05-23 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200517_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('ALL', 'All'), ('BRUNEI', 'Brunei'), ('CAMBODIA', 'Cambodia'), ('HONG KONG', 'Hong Kong'), ('INDONESIA', 'Indonesia'), ('LAOS', 'Laos'), ('MALAYSIA', 'Malaysia'), ('MONGOLIA', 'Mongolia'), ('MYANMAR', 'Myanmar'), ('PAKISTAN', 'Pakistan'), ('PHILIPPINES', 'Philippines'), ('SINGAPORE', 'Singapore'), ('THAILAND', 'Thailand'), ('VIETNAM', 'Vietnam')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
