# Generated by Django 2.2 on 2020-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200523_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('ALL', 'All'), ('BRUNEI', 'Brunei'), ('CAMBODIA', 'Cambodia'), ('HONG KONG', 'Hong Kong'), ('INDONESIA', 'Indonesia'), ('LAOS', 'Laos'), ('MALAYSIA', 'Malaysia'), ('MONGOLIA', 'Mongolia'), ('MYANMAR', 'Myanmar'), ('PAKISTAN', 'Pakistan'), ('PHILIPPINES', 'Philippines'), ('SINGAPORE', 'Singapore'), ('THAILAND', 'Thailand'), ('VIETNAM', 'Vietnam')], default='All', max_length=20),
        ),
    ]
