# Generated by Django 2.2 on 2020-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200526_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('ALL COUNTRIES', 'All Countries'), ('BRUNEI', 'Brunei'), ('CAMBODIA', 'Cambodia'), ('HONG KONG', 'Hong Kong'), ('INDONESIA', 'Indonesia'), ('LAOS', 'Laos'), ('MALAYSIA', 'Malaysia'), ('MONGOLIA', 'Mongolia'), ('MYANMAR', 'Myanmar'), ('PAKISTAN', 'Pakistan'), ('PHILIPPINES', 'Philippines'), ('SINGAPORE', 'Singapore'), ('THAILAND', 'Thailand'), ('VIETNAM', 'Vietnam')], default='All', max_length=20),
        ),
    ]
