# Generated by Django 2.2 on 2020-06-01 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200529_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('PROPOSAL', 'proposal'), ('E-PROOF', 'e-proof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual'), ('MISCELLANEOUS', 'miscellaneous')], default='miscellaneous', max_length=20),
        ),
    ]
