# Generated by Django 2.2 on 2020-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200601_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('PROPOSAL', 'proposal'), ('EPROOF', 'eproof'), ('POWERPOINT', 'powerpoint'), ('BROCHURE', 'brochure'), ('CERTIFICATE', 'certificate'), ('MANUAL', 'manual'), ('MISCELLANEOUS', 'miscellaneous')], default='miscellaneous', max_length=20),
        ),
    ]
