# Generated by Django 2.2 on 2020-05-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200526_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contributor',
        ),
    ]
