# Generated by Django 2.2 on 2020-05-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20200526_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='summary',
        ),
    ]
