# Generated by Django 2.2 on 2020-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20200526_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='pdf',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000),
        ),
    ]
