# Generated by Django 2.2 on 2020-05-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_reseller',
        ),
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.CharField(default='NIL', max_length=100),
        ),
    ]
