# Generated by Django 2.2.6 on 2019-12-10 14:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20191210_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='website',
            field=models.URLField(default='www.website.com'),
            preserve_default=False,
        ),
    ]
