# Generated by Django 2.2 on 2020-04-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20191210_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
