# Generated by Django 2.2 on 2020-05-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
