# Generated by Django 2.2 on 2020-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200504_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
