# Generated by Django 2.2 on 2020-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200504_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
