# Generated by Django 2.2 on 2020-05-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='name',
        ),
    ]
