# Generated by Django 2.2 on 2020-05-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_memberprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='email',
            new_name='username',
        ),
    ]
