# Generated by Django 2.2 on 2020-05-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200508_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='age',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
