# Generated by Django 2.2 on 2020-05-23 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20200515_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='mysettings_itemsperpage',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='join_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
