# Generated by Django 2.2 on 2020-05-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20200523_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='mysettings_itemsperpage',
            new_name='items_per_page',
        ),
    ]
