# Generated by Django 2.2 on 2020-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200523_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(choices=[('sales', 'SALES'), ('business development', 'BUSINESS DEVELOPMENT'), ('marketing', 'MARKETING'), ('technical support', 'TECHNICAL SUPPORT'), ('research & development', 'RESEARCH & DEVELOPMENT'), ('finance', 'FINANCE'), ('legal', 'LEGAL')], default='sales', max_length=20),
        ),
    ]
