# Generated by Django 2.2 on 2020-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20200527_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(default='photos/pic1.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
