# Generated by Django 2.2 on 2020-05-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20200530_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(choices=[('Sales', 'SALES'), ('Business Development', 'BUSINESS DEVELOPMENT'), ('Marketing', 'MARKETING'), ('Technical Support', 'TECHNICAL SUPPORT'), ('Research & Development', 'RESEARCH & DEVELOPMENT'), ('Finance', 'FINANCE'), ('Legal', 'LEGAL')], default='Sales', max_length=20),
        ),
    ]
