# Generated by Django 2.2 on 2020-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20200530_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
